config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'

  


  # static high voltage pages
  # this has to be at the bottom of routes file
  # or else it will block all other routes
  # get "/*id" => 'pages#show', as: :page, format: false
  # root to: 'pages#show', id: 'blog'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.

  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_action :authenticate_user!, :unless => :hvolt_page?

  def hvolt_page?
  	%w(/blog /contact /about).include?(request.path)
  end  

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<div class="col-lg-5">
    <h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>
</div>

app/views/chat_rooms/new.html.erb
<div class="col-lg-5"><h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="col-lg-8">
  <h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<hr>

<%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% content_for :title do %>Rails 5 ActionCable Chat<% end %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bootstrap Rails 5 ActionCable Chat" %>">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- Fonts -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

  </head>
  <body>

<div class="brand">Rails 5 ActionCable Chat</div>
    <div class="address-bar">Desarrollado con Cloud9 IDE | Desplegado sobre Heroku</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
    
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Rails 5 ActionCable Chat</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Principal', root_path %>
                    </li>
                    <li>
                        <%= link_to 'Acerca de', page_path('about') %>
                    </li>
                    <li>
                        <%= link_to 'Blog', page_path('blog') %>
                    </li>
                    <li>
                        <%= link_to 'Contacto', page_path('contact') %>
                    </li>

    <% if user_signed_in? %>
 <!--     
                  <li>
                    <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
                  </li>
-->               
      <li class="active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

    <% else %>
      <li class="active">
        <%= link_to 'Log in', root_path(:anchor => 'login') %>
      </li>            
    <% end %>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
<% if not user_signed_in? %>
        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <%= image_tag("slide-1.jpg", class: "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-2.jpg", class: "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-3.jpg", class: "img-responsive img-full") %>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Bienvenido a</small>
                    </h2>
                    <h1 class="brand-name">Rails 5 ActionCable Chat</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>Por
                            <strong>Víctor Casas San Miguel</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>
<% end %>


        <div  id="login" class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">acceso a las
                        <strong>salas de chat</strong>
                    </h2>
                    <hr>
                    <div class="container">
<div class="col-lg-3"></div>
<%= yield %>
</div>
                </div>
            </div>
        </div>
            <% if not user_signed_in? %>
            <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Cómo funciona
                        <strong>ActionCable</strong>
                    </h2>
                    <hr>
                    <%= image_tag("intro-pic.jpg", class: "img-responsive img-border img-left") %>
                    <hr class="visible-xs">
                    <p>Una de las novedades de Rails 5 es la solución oficial para integrar WebSockets con Rails, llamada ActionCable.
                    </p>
                    <p>A diferencia de HTTP, WebSockets es un tecnología que permite mantener una conexión abierta entre el cliente y el servidor, proporcionando un canal de comunicación bidireccional y full-duplex sobre un único socket TCP.</p>
                    <div id="collapse" class="collapse">  
                    <p>De acuerdo con el sito oficial en <a href="https://github.com/rails/rails/tree/master/actioncable" target="_blank">GitHub</a>, de ActionCable: “ActionCable integra perfectamente WebSockets con el resto de tu aplicación Rails. Permite desarrollar funciones de tiempo real en Ruby con el mismo estilo y forma que el resto de tu aplicación Rails, sin perder en rendimiento y escalabilidad. Proporciona una solución completa tanto desde el lado del cliente con JavaScript como del lado del servidor con Ruby. Tienes acceso a tu modelo de dominio completo escrito con Active Record o el ORM de tu elección.”
                    </p>
                    </div>
                    <button type="button" class="btn btn-default btn-sm" data-toggle="collapse" data-target="#collapse">Leer más</button>

                </div>
            </div>
        </div>
        <% end %>
    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://google.com/+VíctorCasasSanMiguel">Víctor Casas San Miguel</a> 2017</p>
                </div>
            </div>
        </div>
    </footer>
    
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>
</html>

app/views/layouts/static.html.erb
<%= yield %>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% content_for :title do %>Rails 5 ActionCable Chat<% end %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bootstrap Rails 5 ActionCable Chat" %>">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- Fonts -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

  </head>
    
      <body>

<div class="brand">Rails 5 ActionCable Chat</div>
    <div class="address-bar">Desarrollado con Cloud9 IDE | Desplegado sobre Heroku</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
    
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Rails 5 ActionCable Chat</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Principal', root_path%>
                    </li>
                    <li>
                        <%= link_to 'Acerca de', page_path('about') %>
                    </li>
                    <li>
                        <%= link_to 'Blog', page_path('blog') %>
                    </li>
                    <li>
                        <%= link_to 'Contacto', page_path('contact') %>
                    </li>
                       <% if user_signed_in? %>
 <!--     
                  <li>
                    <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
                  </li>
-->               
      <li class="active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

      <% else %>
      <li class="active">
        <%= link_to 'Log in', root_path(:anchor => 'login') %>
      </li>             
      <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Acerca de
                        <strong>Rails 5 ActionCable Chat</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("slide-2.jpg", class: "img-responsive img-border-left") %>
                </div>
                <div class="col-md-6">
                    <p>Una de las novedades de Rails 5 es la solución oficial para integrar WebSockets con Rails, llamada ActionCable.</p>
                    <p>A diferencia de HTTP, WebSockets es un tecnología que permite mantener una conexión abierta entre el cliente y el servidor, proporcionando un canal de comunicación bidireccional y full-duplex sobre un único socket TCP.</p>
                    <p>De acuerdo con el sito oficial en <a href="https://github.com/rails/rails/tree/master/actioncable" target="_blank">GitHub</a>, de ActionCable: “ActionCable integra perfectamente WebSockets con el resto de tu aplicación Rails. Permite desarrollar funciones de tiempo real en Ruby con el mismo estilo y forma que el resto de tu aplicación Rails, sin perder en rendimiento y escalabilidad. Proporciona una solución completa tanto desde el lado del cliente con JavaScript como del lado del servidor con Ruby. Tienes acceso a tu modelo de dominio completo escrito con Active Record o el ORM de tu elección.”
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Tecnologías
                        <strong>empleadas</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <a href="http://rubyonrails.org/" target="_blank">
                      <%= image_tag("rails.jpg", class: "img-responsive") %>
                    </a>
                    <h3>Rails 5
                        <small>Backend</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <a href="http://getbootstrap.com/" target="_blank">
                      <%= image_tag("bootstrap.jpg", class: "img-responsive") %>
                    </a>
                    <h3>Bootstrap
                        <small>Frontend</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <a href="http://www.heroku.com/" target="_blank">
                      <%= image_tag("heroku.jpg", class: "img-responsive") %>
                    </a>
                    <h3>Heroku
                        <small>Cloud Server</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://google.com/+VíctorCasasSanMiguel">Víctor Casas San Miguel</a> 2017</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/views/pages/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% content_for :title do %>Rails 5 ActionCable Chat<% end %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bootstrap Rails 5 ActionCable Chat" %>">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- Fonts -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

  </head>
    
      <body>

<div class="brand">Rails 5 ActionCable Chat</div>
    <div class="address-bar">Desarrollado con Cloud9 IDE | Desplegado sobre Heroku</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
    
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Rails 5 ActionCable Chat</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Principal', root_path%>
                    </li>
                    <li>
                        <%= link_to 'Acerca de', page_path('about') %>
                    </li>
                    <li>
                        <%= link_to 'Blog', page_path('blog') %>
                    </li>
                    <li>
                        <%= link_to 'Contacto', page_path('contact') %>
                    </li>
                       <% if user_signed_in? %>
 <!--     
                  <li>
                    <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
                  </li>
-->               
      <li class="active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

      <% else %>
      <li class="active">
        <%= link_to 'Log in', root_path(:anchor => 'login') %>
      </li>              
      <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
           <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Rails 5 ActionCable Chat
                        <strong>blog</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-1.jpg" alt="">
                    <h2>Tiempo Real
                        <br>
                        <small>Febrero 4, 2017</small>
                    </h2>
                    <p>De acuerdo con el sito oficial en <a href="https://github.com/rails/rails/tree/master/actioncable" target="_blank">GitHub</a>, de ActionCable: “ActionCable integra perfectamente WebSockets con el resto de tu aplicación Rails. Permite desarrollar funciones de tiempo real en Ruby con el mismo estilo y forma que el resto de tu aplicación Rails, sin perder en rendimiento y escalabilidad. Proporciona una solución completa tanto desde el lado del cliente con JavaScript como del lado del servidor con Ruby. Tienes acceso a tu modelo de dominio completo escrito con Active Record o el ORM de tu elección.”
                    </p>
                    <a href="#" class="btn btn-default btn-lg">Leer Más</a>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-2.jpg" alt="">
                    <h2>WebSockets
                        <br>
                        <small>Enero 31, 2017</small>
                    </h2>
                    <p>A diferencia de HTTP, WebSockets es un tecnología que permite mantener una conexión abierta entre el cliente y el servidor, proporcionando un canal de comunicación bidireccional y full-duplex sobre un único socket TCP.</p>
                    <a href="#" class="btn btn-default btn-lg">Leer Más</a>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <img class="img-responsive img-border img-full" src="img/slide-3.jpg" alt="">
                    <h2>ActionCable
                        <br>
                        <small>Enero 30, 2017</small>
                    </h2>
                    <p>Una de las novedades de Rails 5 es la solución oficial para integrar WebSockets con Rails, llamada ActionCable.</p>
                    <a href="#" class="btn btn-default btn-lg">Leer Más</a>
                    <hr>
                </div>
                <div class="col-lg-12 text-center">
                    <ul class="pager">
                        <li class="previous"><a href="#">&larr; Antiguos</a>
                        </li>
                        <li class="next"><a href="#">Nuevos &rarr;</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://google.com/+VíctorCasasSanMiguel">Víctor Casas San Miguel</a> 2017</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>